### ISSUE TITLE
flip restart policy

### ISSUE THREAD

**Issue by ls1xt** [BioroboticsLab/organization#13]
Some times flip hangs and need a restart.
This needs quite huge coordination, as many people use flip. 
My proposal:
1. Announce flip downtime on the [#flip](https://fubioroboticslab.slack.com/messages/flip/) slack channel.
2. wait 15 minutes. Check if you can connect from another pc or connection.
3. If nobody raises concerns, reboot flip, else agree over slack on the further procedure.

If anybody announced on the #flip slack channel that she needs flip to be running no matter what, flip
will not be rebooted.

With this procedure flip can be restarted fast and still no work should be lost.

**Comment by walachey** [comment]
Do we know WHY flip sometimes hangs?

Could it be that e.g. the SSH daemon is randomly killed by the OS because we use too much RAM?
That would then be /solved/ by adding the swap partition (as @nebw suggested).

Otherwise I'm fine with this. If flip is irrecoverably lost, we need to restart asap anyway.

**Comment by hmoenck** [comment]
Apparently we easily use >24GB of RAM. Adding some 20GB of swap might solve the crash, but flip will be terribly slow. That's why we generally do not want to run out of RAM. Adding swap space may only help to manually track down the issue and solve it. However, this does not prevent deficiencies.
Is there some kind software to supervise resource usage intelligently? Eg. logging who/what is the evil-doer, contacting admins/responsible people via mail (or sth) if resources are about to run out. Maybe automatically kill some tasks (in a smarter way than the kernel). This may be applied to RAM, HDD space, GPU, ...? We encountered several shortages in the past.

**Comment by ls1xt** [comment]
A swap partition is a absolute must. I had the idea to write a small python script to monitor flip. If at anytime the ram or gpu ram are over e.g 90% full a message is posted in the #flip channel.

**Comment by walachey** [comment]
We could also get a 64GB SSD for around 60€ and use that as the swap partition! That'd probably even still be okay-ishly fast.

**Comment by nebw** [comment]
I'm pretty sure that the random crashes of flip are somehow related to the docker issue. It's pretty unlikely that sshd is getting killed by linux's OOM killer because it favors processes that up a lot of memory. Also, last time we tried to debug the problem locally but there was also not output on the screen.

**Comment by ktugan** [comment]
Does the crashing problem still exist? If not it should be closed.

Restart policy is now under [https://github.com/BioroboticsLab/organization/wiki/Flip#restart-policy](https://github.com/BioroboticsLab/organization/wiki/Flip#restart-policy)

**Comment by ktugan** [comment]
seems not relevant anymore, reopen if problem persists
